# Generated by Django 6.0.5 on 2026-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='missing_vehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='safe_vehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_vehicles',
            field=models.IntegerField(default=0),
        ),
    ]
