# Generated by Django 6.0.5 on 2026-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_analysis_missing_vehicles_analysis_safe_vehicles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='bikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='buses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='trucks',
            field=models.IntegerField(default=0),
        ),
    ]
